# 01doris-fe.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: doriscluster-helm
    app.kubernetes.io/component: fe
  name: doriscluster-helm-fe-service
spec:
  ports:
    - name: http-port
      port: 8030
      protocol: TCP
      targetPort: 8030
    - name: rpc-port
      port: 9020
      protocol: TCP
      targetPort: 9020
    - name: query-port
      port: 9030
      protocol: TCP
      targetPort: 9030
    - name: edit-log-port
      port: 9010
      protocol: TCP
      targetPort: 9010
  selector:
    app.kubernetes.io/name: doriscluster-helm-fe
    app.kubernetes.io/component: fe
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: doriscluster-helm
    app.kubernetes.io/component: fe
  name: doriscluster-helm-fe-internal
spec:
  clusterIP: None
  ports:
    - name: query-port
      port: 9030
      protocol: TCP
      targetPort: 9030
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: doriscluster-helm-fe
    app.kubernetes.io/component: fe
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: doriscluster-helm
    app.kubernetes.io/component: fe
  name: doriscluster-helm-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: doriscluster-helm-fe
      app.kubernetes.io/component: fe
  serviceName: doriscluster-helm-fe-internal
  # FIXME 首次启动需要串行启动，因为第一个启动完成的要作为master节点, 而后续启动的节点才能指定master的地址
  # 非首次启动需要并行启动， 因为如果第一个节点挂掉并且数据丢失，那么它启动会作为一个新节点，但是又处于第一启动顺位，无法加入集群，从而作为单独集群启动，后续原集群节点启动也无法将它加入原集群，导致整个集群无法启动
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app.doris.cluster: doriscluster-helm
        app.kubernetes.io/name: doriscluster-helm-fe
        app.kubernetes.io/component: fe
      name: doriscluster-helm-fe
    spec:
      # initContainers:
      #   - name: init-start-cmd
      #     image: docker.io/library/mariadb:11.4.1-rc
      #     command:
      #       - echo 
      #       - "enable_fqdn_mode = true" 
      #       - ">>"
      #       - /opt/apache-doris/fe/conf/fe.conf
      #     env:
      #       - name: FOLLOWER_URIS
      #         value: doriscluster-helm-fe-0,doriscluster-helm-fe-1,doriscluster-helm-fe-2
      #       - name: ENV_FE_ADDR
      #         value: doriscluster-helm-fe-service
      #       - name: POD_ID
      #         valueFrom:
      #           fieldRef:
      #             fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
      #     volumeMounts:
      #       - mountPath: /opt/apache-doris/fe/doris-meta
      #         name: fe-meta
      containers:
        - args:
            - $(ENV_FE_ADDR)
            # - org.apache.doris.DorisFE
            # - $(HELPER_KEY)
            # - $(HELPER_VAL)
          command:
            - bash
            - -x
            - /opt/apache-doris/fe_entrypoint.sh
            # - java
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            # - name: POD_ID
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            # - name: CONFIGMAP_MOUNT_PATH
            #   value: /etc/doris
            # - name: ENABLE_FQDN_MODE
            #   value: "true"
            # - name: JAVA_OPTS
            #   value: "-Xmx1024m"
            # - name: CLASSPATH
            #   value: "/opt/apache-doris/fe/lib/doris-fe.jar:/opt/apache-doris/fe/lib/*"
            # - name: USER
            #   value: root
            - name: DORIS_ROOT
              value: /opt/apache-doris
            - name: ENV_FE_ADDR
              value: doriscluster-helm-fe-service
            # - name: FE_QUERY_PORT
            #   value: "9030"
            # spec.replicas 如果大于这个则多出来的节点会以observer加入
            - name: ELECT_NUMBER
              value: "3"
          image: selectdb/doris.fe-ubuntu:2.0.3
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/apache-doris/fe_prestop.sh
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9030
            timeoutSeconds: 180
          name: fe
          ports:
            - containerPort: 8030
              name: http-port
              protocol: TCP
            - containerPort: 9020
              name: rpc-port
              protocol: TCP
            - containerPort: 9030
              name: query-port
              protocol: TCP
            - containerPort: 9010
              name: edit-log-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8030
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 500Mi
          startupProbe:
            failureThreshold: 60
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9030
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
            - mountPath: /opt/apache-doris/fe/doris-meta
              name: fe-meta
            - mountPath: /opt/apache-doris/fe/log
              name: fe-log
            # - mountPath: /opt/apache-doris/fe/conf
            #   name: fe-conf
      terminationGracePeriodSeconds: 30
      volumes:
        # - emptyDir: {}
        #   name: fe-meta
        - downwardAPI:
            defaultMode: 420
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels
                path: labels
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
                path: annotations
          name: podinfo
        # - name: fe-conf
        #   configMap:
        #     name: fe-conf
        #     items: 
        #       - key: fe.conf
        #         path: fe.conf
  # updateStrategy:
  #   rollingUpdate:
  #     maxUnavailable: "100%"
  volumeClaimTemplates:
    - metadata:
        name: fe-meta
        labels:
          app.doris.cluster: doriscluster-helm
          app.kubernetes.io/name: doriscluster-helm-fe
          app.kubernetes.io/component: fe
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: fe-log
        labels:
          app.doris.cluster: doriscluster-helm
          app.kubernetes.io/name: doriscluster-helm-fe
          app.kubernetes.io/component: fe
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
