Vagrant.configure("2") do |config|
    config.trigger.before :up do |trigger|
        trigger.info = "Creating 'NATSwitch' Hyper-V switch if it does not exist..."
    
        trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./script/create-nat-hyperv-switch.ps1"}
    end
    
    config.trigger.before :reload do |trigger|
        trigger.info = "Setting Hyper-V switch to 'NATSwitch' to allow for static IP..."
    
        trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./script/set-hyperv-switch.ps1"}
    end
    
    # exec script in vm, path: the path of host
    config.vm.provision "shell", path: "./script/init-vm.sh"

    # primary: the root file system on
    config.vm.disk :disk, size: "40GB", primary: true

    config.vm.provider "hyperv" do |hv|
        hv.vmname = "ubt1"
        hv.cpus = 4
        #MB
        hv.memory = 4096
        hv.maxmemory = nil
        hv.vlan_id  = 20
    end
    config.vm.hostname = "ubt1"
    
    # define multi vm
    # config.vm.define "ubt1" do |ubt1|
    #     ubt1.vm.hostname = "ubt1"
    #     ubt1.vm.provider "hyperv" do |hv2|
    #         hv2.vmname = "ubt1"
    #     end
    #     ubt1.vm.cloud_init :user_data do |cloud_init2|
    #         cloud_init2.content_type = "text/cloud-config"
    #         cloud_init2.path = "config1.cfg"
    #     end
    # end

    # config.vm.synced_folder '.', '/vagrant', {
    #   type: 'smb', mount_options: ['vers=3.0'],
    #   smb_username: ENV['VAGRANT_SMB_USERNAME'],
    #   smb_password: ENV['VAGRANT_SMB_PASSWORD']
    # }
    config.vm.box = "generic/ubuntu2204"

    # Simplified form
    config.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "config.cfg"

    # block form 
    # config.vm.cloud_init :user_data do |cloud_init|
    #     cloud_init.content_type = "text/cloud-config"
    #     cloud_init.path = "config.cfg"
    # end

end