---
# Source: tdengine/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-tdengine-taoscfg
  labels:
    helm.sh/chart: tdengine-3.0.2
    app.kubernetes.io/name: tdengine
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.0.2.2"
    app.kubernetes.io/managed-by: Helm
data:
  CLUSTER: "1"
  TAOS_REPLICA: "3"
---
# Source: tdengine/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-tdengine
  labels:
    helm.sh/chart: tdengine-3.0.2
    app.kubernetes.io/name: tdengine
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.0.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports: 
    - name: tcp0
      port: 6030
      protocol: TCP
    - name: tcp1
      port: 6041
      protocol: TCP
    - name: tcp2
      port: 6042
      protocol: TCP
    - name: tcp3
      port: 6043
      protocol: TCP
    - name: tcp4
      port: 6044
      protocol: TCP
    - name: tcp5
      port: 6046
      protocol: TCP
    - name: tcp6
      port: 6047
      protocol: TCP
    - name: tcp7
      port: 6048
      protocol: TCP
    - name: tcp8
      port: 6049
      protocol: TCP
    - name: tcp9
      port: 6060
      protocol: TCP
    
    - name: udp0
      port: 6044
      protocol: UDP
    - name: udp1
      port: 6045
      protocol: UDP
  selector:
    app.kubernetes.io/name: tdengine
    app.kubernetes.io/instance: release-name
    app: "taosd"
---
# Source: tdengine/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-tdengine
  labels:
    helm.sh/chart: tdengine-3.0.2
    app.kubernetes.io/name: tdengine
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.0.2.2"
    app.kubernetes.io/managed-by: Helm
    app: taosd
spec:
  serviceName: release-name-tdengine
  replicas: 3
  # podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: tdengine
      app.kubernetes.io/instance: release-name
      app: taosd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tdengine
        app.kubernetes.io/instance: release-name
        app: taosd
    spec:
      containers:
        - name: tdengine
          image: "tdengine/tdengine:3.2.3.0"
          imagePullPolicy: 
          ports: 
          - name: tcp0
            containerPort: 6030
            protocol: TCP
          - name: tcp1
            containerPort: 6041
            protocol: TCP
          - name: tcp2
            containerPort: 6042
            protocol: TCP
          - name: tcp3
            containerPort: 6043
            protocol: TCP
          - name: tcp4
            containerPort: 6044
            protocol: TCP
          - name: tcp5
            containerPort: 6046
            protocol: TCP
          - name: tcp6
            containerPort: 6047
            protocol: TCP
          - name: tcp7
            containerPort: 6048
            protocol: TCP
          - name: tcp8
            containerPort: 6049
            protocol: TCP
          - name: tcp9
            containerPort: 6060
            protocol: TCP
          
          - name: udp0
            containerPort: 6044
            protocol: UDP
          - name: udp1
            containerPort: 6045
            protocol: UDP

          env:
          # POD_NAME for FQDN config
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # SERVICE_NAME and NAMESPACE for fqdn resolve
          - name: SERVICE_NAME
            value: release-name-tdengine
          - name: STS_NAME
            value: release-name-tdengine
          - name: STS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # TZ for timezone settings, we recommend to always set it.
          - name: TZ
            value: Asia/Shanghai
          # TAOS_ prefix will configured in taos.cfg, strip prefix and camelCase.
          - name: TAOS_SERVER_PORT
            value: "6030"
          # Must set if you want a cluster.
          - name: TAOS_FIRST_EP
            value: '$(STS_NAME)-0.$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local:$(TAOS_SERVER_PORT)'
          # TAOS_FQND should always be setted in k8s env.
          - name: TAOS_FQDN
            value: '$(POD_NAME).$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local'

          envFrom:
          - configMapRef:
              name: release-name-tdengine-taoscfg
          volumeMounts:
          - name: release-name-tdengine-taosdata
            mountPath: /var/lib/taos
          - name: release-name-tdengine-taoslog
            mountPath: /var/log/taos
          readinessProbe:
            exec:
              command:
              - taos-check
            initialDelaySeconds: 5
            timeoutSeconds: 5000
          livenessProbe:
            exec:
              command:
              - taos-check
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            # privileged: true
            # allowPrivilegeEscalation: true
            # runAsUser: 0
            # runAsGroup: 0
            # readOnlyRootFilesystem: false
            # allowedCapabilities:
            # - CAP_SYS_ADMIN
            # - CHOWN
            # - DAC_OVERRIDE
            # - SETGID
            # - SETUID
            # - NET_BIND_SERVICE
            # AllowedHostPaths:
            # - pathPrefix: "/proc"
            #   readOnly: true # 仅允许只读模式挂载
            # - pathPrefix: "/sys"
            #   readOnly: true # 仅允许只读模式挂载
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: release-name-tdengine-taosdata
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "2Gi"
  - metadata:
      name: release-name-tdengine-taoslog
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "2Gi"
