# createCert: false必须和esConfig或者环境变量禁用ssl一起配置否则无法启动
createCert: false
protocol: http

secret:
  enabled: true
  # 默认值是随机的，保存早k8s的 secret elasticsearch-master-credentials 中
  password: es123456

# 默认值
clusterName: "elasticsearch"
nodeGroup: "master"
roles:
  - master


# extraEnvs: 
#  - name: xpack.security.enabled
#    value: false
#  - name: xpack.security.transport.ssl.enabled
#    value: false
#  - name: xpack.security.http.ssl.enabled
#    value: false

# 禁用ssl esConfig 配置必须和 createCert: false 一起配置，否则无法启动
esConfig:
  elasticsearch.yml: |
    node.store.allow_mmap: false
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false


ingress:
  enabled: true
  className: "public"
  hosts:
    - host: console.elasticsearch.local
      paths:
        - path: /

tests:
  enabled: false

# # Disable privileged init Container creation.
# sysctlInitContainer:
#   enabled: false

# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
# 有两个java线程 启动线程使用了最大64m内存, 另外 还有堆外内存
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 100M