
apiVersion: v1
kind: Pod
metadata:
  name: runasuser-pod
spec:
  containers:
    - name: runasuser-container
      image: busybox
      args: 
        - /bin/sh
        - -c
        - 'nc -l 9000'
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
  restartPolicy: Never