
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc1
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: test-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-nginx
    spec:
      containers:
        - name: test-nginx
          image: docker.io/library/nginx
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi
      subdomain: pod-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
spec:
  ports:
  - name: http
    port: 9030
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: test-nginx

# kubectl run -it --rm busybox --image=busybox
# kubectl run -it --rm curl --image=curlimages/curl -- sh