namespace: mw

resources:
- namespace.yaml

secretGenerator:
- name:  elasticsearch-master-crt
  namespace: mw
  type: kubernetes.io/tls
  files:
    - tls/tls.crt
    - tls/tls.key
    - tls/ca.crt

helmCharts:
- name: elasticsearch
  repo: https://charts.bitnami.com/bitnami
  version: 19.17.0
  releaseName: elasticsearch
  namespace: mw
  # override with these custom values
  valuesFile: values-es.yaml