

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: sonarqube.lo-k8s

  # Set the ingressClassName on the ingress record
  ingressClassName: nginx

# List of plugins to install
# 这里设置会清除目录 /opt/sonarqube/extensions/plugins/下的所有内容, 考虑不要设置此项，直接将插件包挂载到此目录
# 这里会在安装时通过curl下载，如果下载错误，可能导致安装失败
# plugins:
#   install: 
#     - "https://mirror.ghproxy.com/https://github.com/checkstyle/sonar-checkstyle/releases/download/10.19.0/checkstyle-sonar-plugin-10.19.0.jar"
#     - "https://repo.maven.apache.org/maven2/com/github/spotbugs/sonar-findbugs-plugin/4.3.0/sonar-findbugs-plugin-4.3.0.jar"
#     - "https://mirror.ghproxy.com/https://github.com/donhui/sonar-mybatis/releases/download/1.0.8/sonar-mybatis-plugin-1.0.8.jar"
#     - "https://mirror.ghproxy.com/https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/5.0.0/sonar-dependency-check-plugin-5.0.0.jar"


## Override JDBC values
## for external Databases
jdbcOverwrite:
  # If enable the JDBC Overwrite, make sure to set `postgresql.enabled=false`
  enabled: true
  # The JDBC url of the external DB
  jdbcUrl: "jdbc:postgresql://postgresql:5432/sonar_db"
  # The DB user that should be used for the JDBC connection
  jdbcUsername: "sonarq"
  # Use this if you don't mind the DB password getting stored in plain text within the values file
  jdbcPassword: "Sq1234"

postgresql:
  enabled: false

persistence:
  enabled: true

  ## Specify an existing volume claim instead of creating a new one.
  ## When using this option all following options like storageClass, accessMode and size are ignored.
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: microk8s-hostpath
  size: 2Gi

account:
# The values can be set to define the current and the (new) custom admin passwords at the startup (the username will remain "admin")
  adminPassword: admin
  currentAdminPassword: Sq1234