namespace: pulsar
namespaceCreate: true
# kube-prometheus-stack:
#   enabled: false
#   prometheusOperator:
#     enabled: false
#   grafana:
#     enabled: false
#   alertmanager:
#     enabled: false
#   prometheus:
#     enabled: false


## deployed withh emptyDir
volumes:
  persistence: false

# disabled AntiAffinity
affinity:
  anti_affinity: false

# disable auto recovery
components:
  autorecovery: false
  pulsar_manager: true

zookeeper:
  replicaCount: 3
  # podMonitor: 
  #   enabled: false

bookkeeper:
  replicaCount: 3
  # podMonitor: 
  #   enabled: false

broker:
  replicaCount: 3
  # podMonitor: 
  #   enabled: false
  configData:
    ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
    ## without persistence
    autoSkipNonRecoverableData: "true"
    # storage settings
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"

proxy:
  replicaCount: 1
  # podMonitor: 
  #   enabled: false

pulsar_manager:
  configData:
    ENV_SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
    SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
    PULSAR_MANAGER_OPTS: " -Dlog4j2.formatMsgNoLookups=true"